tls: more generic function to set cafile and capath
baresip/re pull request #84
Opened 2021-03-16 09:06 UTC by cHuberCoffee

2021-03-16 12:51 UTC, sreimers requested changes

2021-03-16 12:51 UTC, sreimers commented on src/tls/openssl/tls.c
>  		return EINVAL;
Maybe `ENOENT` is a better return code.

2021-03-16 12:51 UTC, sreimers commented on src/tls/openssl/tls.c
> +
Can you add a negative test case (check for wrong cafile/capath) for `tls_add_cafile_path` in https://github.com/baresip/retest?

2021-03-17 09:41 UTC, sreimers commented on src/tls/openssl/tls.c
> +		return ENOENT;
There is a `ENOTDIR` for this case.

2021-03-17 09:55 UTC, sreimers approved these changes

2021-03-17 13:27 UTC, juha-h commented
These should be improved:
```
 * @param cafile PEM file with CA certificate
 * @param capath Path containing CA certificates
```
Isn't it so that also cafile file can contain many ca certificates?

Path does not contain ca certificates, but files than contain ca certificates.

2021-03-18 11:18 UTC, merged